//1. the constructor have same named as the class have.
//2. the constructor  is to perform initialization.
//3.there is no return type of constructor.
/* 4. if there is no constructor in class then the default constructor
 is automatically generate default constructor only when we have not provided any constructor in  class.*/
// 5. the constructor generated by the compiler is known as default constructor
// 6. the access modifier of default constructor is same as class modifier.
//7. default constructor only contain super() --- it is no argument call to super class constructor.

// 8. inheritance and overriding is not applicable in constructor.
package com.devi;
public class constructor {

    //declaration  of local variables
    int a;
    int b;

    // CONSTRUCTOR
    public constructor() {
        //initialization the value of a and b
        a = 10;
        b = 20;
        int c = a + b; // declared a third variable and initialize it with the value of a+b;
        System.out.println("the sum is: " + c);

    }


    // PARAMETERIZES CONSTRUCTOR
    public constructor(int a){ //providing a parameter of integer type.
        this.a=a;  //this.a specifies the current object a
        }

        //OVERLOADING PARAMETERIZED CONSTRUCTOR.
    public constructor(int a,int b){ //initializing this constructor with 2 integer values for the overloading
        this.a=a;
        this.b=b;
    }

    public static  void main(String[] args)
    {
        // the new is responsible for the creation of object
        constructor obj = new constructor(); // this is for the  constructor as no parameter is given in this

        constructor obj1 =new constructor(3);//this is for the parameterized constructor having  a.
        System.out.println("the value of a is: "+ obj1.a);//called a using dot operator.

        constructor obj2 = new constructor(4,5); //this is for the overloading purpose of the constructor.
        System.out.println("the value of a is :"+obj2.a+"\nthe value of b is :"+obj2.b);

    }


}
